INSERT INTO country(iso2_code, iso3_code, name) VALUES ('AF', 'AFG', 'Afghanistan');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('AX', 'ALA', 'Åland Islands');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('AL', 'ALB', 'Albania');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('DZ', 'DZA', 'Algeria');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('AS', 'ASM', 'American Samoa');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('AD', 'AND', 'Andorra');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('AO', 'AGO', 'Angola');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('AI', 'AIA', 'Anguilla');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('AQ', 'ATA', 'Antarctica');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('AG', 'ATG', 'Antigua and Barbuda');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('AR', 'ARG', 'Argentina');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('AM', 'ARM', 'Armenia');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('AW', 'ABW', 'Aruba');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('AU', 'AUS', 'Australia');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('AT', 'AUT', 'Austria');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('AZ', 'AZE', 'Azerbaijan');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('BS', 'BHS', 'Bahamas');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('BH', 'BHR', 'Bahrain');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('BD', 'BGD', 'Bangladesh');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('BB', 'BRB', 'Barbados');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('BY', 'BLR', 'Belarus');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('BE', 'BEL', 'Belgium');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('BZ', 'BLZ', 'Belize');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('BJ', 'BEN', 'Benin');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('BM', 'BMU', 'Bermuda');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('BT', 'BTN', 'Bhutan');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('BO', 'BOL', 'Bolivia');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('BQ', 'BES', 'Bonaire');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('BA', 'BIH', 'Bosnia and Herzegovina');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('BW', 'BWA', 'Botswana');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('BV', 'BVT', 'Bouvet Island');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('BR', 'BRA', 'Brazil');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('IO', 'IOT', 'British Indian Ocean Territory');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('BN', 'BRN', 'Brunei');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('BG', 'BGR', 'Bulgaria');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('BF', 'BFA', 'Burkina Faso');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('BI', 'BDI', 'Burundi');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('KH', 'KHM', 'Cambodia');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('CM', 'CMR', 'Cameroon');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('CA', 'CAN', 'Canada');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('CV', 'CPV', 'Cabo Verde');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('KY', 'CYM', 'Cayman Islands');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('CF', 'CAF', 'Central African Republic');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('TD', 'TCD', 'Chad');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('CL', 'CHL', 'Chile');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('CN', 'CHN', 'China');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('CX', 'CXR', 'Christmas Island');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('CC', 'CCK', 'Cocos Islands');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('CO', 'COL', 'Colombia');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('KM', 'COM', 'Comoros');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('CG', 'COG', 'Congo');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('CD', 'COD', 'Congo-Kinshasa');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('CK', 'COK', 'Cook Islands');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('CR', 'CRI', 'Costa Rica');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('CI', 'CIV', 'Côte d\'Ivoire');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('HR', 'HRV', 'Croatia');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('CU', 'CUB', 'Cuba');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('CW', 'CUW', 'Curaçao');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('CY', 'CYP', 'Cyprus');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('CZ', 'CZE', 'Czech Republic');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('DK', 'DNK', 'Denmark');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('DJ', 'DJI', 'Djibouti');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('DM', 'DMA', 'Dominica');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('DO', 'DOM', 'Dominican Republic');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('EC', 'ECU', 'Ecuador');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('EG', 'EGY', 'Egypt');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('SV', 'SLV', 'El Salvador');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('GQ', 'GNQ', 'Equatorial Guinea');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('ER', 'ERI', 'Eritrea');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('EE', 'EST', 'Estonia');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('ET', 'ETH', 'Ethiopia');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('FK', 'FLK', 'Falkland Islands');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('FO', 'FRO', 'Faroe Islands');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('FJ', 'FJI', 'Fiji');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('FI', 'FIN', 'Finland');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('FR', 'FRA', 'France');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('GF', 'GUF', 'French Guiana');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('PF', 'PYF', 'French Polynesia');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('TF', 'ATF', 'French Southern Territories');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('GA', 'GAB', 'Gabon');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('GM', 'GMB', 'Gambia');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('GE', 'GEO', 'Georgia');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('DE', 'DEU', 'Germany');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('GH', 'GHA', 'Ghana');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('GI', 'GIB', 'Gibraltar');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('GR', 'GRC', 'Greece');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('GL', 'GRL', 'Greenland');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('GD', 'GRD', 'Grenada');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('GP', 'GLP', 'Guadeloupe');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('GU', 'GUM', 'Guam');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('GT', 'GTM', 'Guatemala');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('GG', 'GGY', 'Guernsey');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('GN', 'GIN', 'Guinea');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('GW', 'GNB', 'Guinea-Bissau');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('GY', 'GUY', 'Guyana');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('HT', 'HTI', 'Haiti');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('HM', 'HMD', 'Heard Island and McDonald Islands');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('VA', 'VAT', 'Holy See');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('HN', 'HND', 'Honduras');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('HK', 'HKG', 'Hong Kong');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('HU', 'HUN', 'Hungary');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('IS', 'ISL', 'Iceland');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('IN', 'IND', 'India');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('ID', 'IDN', 'Indonesia');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('IR', 'IRN', 'Iran');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('IQ', 'IRQ', 'Iraq');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('IE', 'IRL', 'Ireland');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('IM', 'IMN', 'Isle of Man');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('IL', 'ISR', 'Israel');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('IT', 'ITA', 'Italy');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('JM', 'JAM', 'Jamaica');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('JP', 'JPN', 'Japan');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('JE', 'JEY', 'Jersey');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('JO', 'JOR', 'Jordan');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('KZ', 'KAZ', 'Kazakhstan');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('KE', 'KEN', 'Kenya');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('KI', 'KIR', 'Kiribati');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('KP', 'PRK', 'North Korea');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('KR', 'KOR', 'South Korea');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('KW', 'KWT', 'Kuwait');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('KG', 'KGZ', 'Kyrgyzstan');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('LA', 'LAO', 'Laos');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('LV', 'LVA', 'Latvia');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('LB', 'LBN', 'Lebanon');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('LS', 'LSO', 'Lesotho');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('LR', 'LBR', 'Liberia');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('LY', 'LBY', 'Libya');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('LI', 'LIE', 'Liechtenstein');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('LT', 'LTU', 'Lithuania');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('LU', 'LUX', 'Luxembourg');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('MO', 'MAC', 'Macao');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('MK', 'MKD', 'Macedonia');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('MG', 'MDG', 'Madagascar');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('MW', 'MWI', 'Malawi');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('MY', 'MYS', 'Malaysia');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('MV', 'MDV', 'Maldives');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('ML', 'MLI', 'Mali');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('MT', 'MLT', 'Malta');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('MH', 'MHL', 'Marshall Islands');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('MQ', 'MTQ', 'Martinique');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('MR', 'MRT', 'Mauritania');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('MU', 'MUS', 'Mauritius');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('YT', 'MYT', 'Mayotte');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('MX', 'MEX', 'Mexico');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('FM', 'FSM', 'Micronesia');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('MD', 'MDA', 'Moldova');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('MC', 'MCO', 'Monaco');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('MN', 'MNG', 'Mongolia');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('ME', 'MNE', 'Montenegro');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('MS', 'MSR', 'Montserrat');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('MA', 'MAR', 'Morocco');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('MZ', 'MOZ', 'Mozambique');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('MM', 'MMR', 'Myanmar');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('NA', 'NAM', 'Namibia');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('NR', 'NRU', 'Nauru');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('NP', 'NPL', 'Nepal');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('NL', 'NLD', 'Netherlands');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('NC', 'NCL', 'New Caledonia');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('NZ', 'NZL', 'New Zealand');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('NI', 'NIC', 'Nicaragua');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('NE', 'NER', 'Niger');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('NG', 'NGA', 'Nigeria');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('NU', 'NIU', 'Niue');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('NF', 'NFK', 'Norfolk Island');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('MP', 'MNP', 'Northern Mariana Islands');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('NO', 'NOR', 'Norway');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('OM', 'OMN', 'Oman');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('PK', 'PAK', 'Pakistan');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('PW', 'PLW', 'Palau');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('PS', 'PSE', 'Palestine');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('PA', 'PAN', 'Panama');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('PG', 'PNG', 'Papua New Guinea');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('PY', 'PRY', 'Paraguay');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('PE', 'PER', 'Peru');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('PH', 'PHL', 'Philippines');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('PN', 'PCN', 'Pitcairn');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('PL', 'POL', 'Poland');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('PT', 'PRT', 'Portugal');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('PR', 'PRI', 'Puerto Rico');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('QA', 'QAT', 'Qatar');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('RE', 'REU', 'Réunion');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('RO', 'ROU', 'Romania');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('RU', 'RUS', 'Russian Federation');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('RW', 'RWA', 'Rwanda');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('BL', 'BLM', 'Saint Barthélemy');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('SH', 'SHN', 'Saint Helena, Ascension and Tristan da Cunha');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('KN', 'KNA', 'Saint Kitts and Nevis');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('LC', 'LCA', 'Saint Lucia');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('MF', 'MAF', 'Saint Martin');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('PM', 'SPM', 'Saint Pierre and Miquelon');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('VC', 'VCT', 'Saint Vincent and the Grenadines');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('WS', 'WSM', 'Samoa');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('SM', 'SMR', 'San Marino');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('ST', 'STP', 'Sao Tome and Principe');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('SA', 'SAU', 'Saudi Arabia');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('SN', 'SEN', 'Senegal');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('RS', 'SRB', 'Serbia');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('SC', 'SYC', 'Seychelles');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('SL', 'SLE', 'Sierra Leone');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('SG', 'SGP', 'Singapore');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('SX', 'SXM', 'Sint Maarten');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('SK', 'SVK', 'Slovakia');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('SI', 'SVN', 'Slovenia');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('SB', 'SLB', 'Solomon Islands');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('SO', 'SOM', 'Somalia');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('ZA', 'ZAF', 'South Africa');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('GS', 'SGS', 'South Georgia and the South Sandwich Islands');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('SS', 'SSD', 'South Sudan');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('ES', 'ESP', 'Spain');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('LK', 'LKA', 'Sri Lanka');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('SD', 'SDN', 'Sudan');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('SR', 'SUR', 'Suriname');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('SJ', 'SJM', 'Svalbard and Jan Mayen');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('SZ', 'SWZ', 'Swaziland');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('SE', 'SWE', 'Sweden');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('CH', 'CHE', 'Switzerland');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('SY', 'SYR', 'Syria');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('TW', 'TWN', 'Taiwan');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('TJ', 'TJK', 'Tajikistan');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('TZ', 'TZA', 'Tanzania');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('TH', 'THA', 'Thailand');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('TL', 'TLS', 'Timor-Leste');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('TG', 'TGO', 'Togo');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('TK', 'TKL', 'Tokelau');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('TO', 'TON', 'Tonga');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('TT', 'TTO', 'Trinidad and Tobago');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('TN', 'TUN', 'Tunisia');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('TR', 'TUR', 'Turkey');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('TM', 'TKM', 'Turkmenistan');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('TC', 'TCA', 'Turks and Caicos Islands');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('TV', 'TUV', 'Tuvalu');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('UG', 'UGA', 'Uganda');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('UA', 'UKR', 'Ukraine');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('AE', 'ARE', 'United Arab Emirates');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('GB', 'GBR', 'United Kingdom');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('US', 'USA', 'United States');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('UM', 'UMI', 'United States Minor Outlying Islands');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('UY', 'URY', 'Uruguay');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('UZ', 'UZB', 'Uzbekistan');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('VU', 'VUT', 'Vanuatu');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('VE', 'VEN', 'Venezuela');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('VN', 'VNM', 'Viet Nam');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('VG', 'VGB', 'Virgin Islands (British)');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('VI', 'VIR', 'Virgin Islands (U.S.)');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('WF', 'WLF', 'Wallis and Futuna');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('EH', 'ESH', 'Western Sahara');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('YE', 'YEM', 'Yemen');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('ZM', 'ZMB', 'Zambia');
INSERT INTO country(iso2_code, iso3_code, name) VALUES ('ZW', 'ZWE', 'Zimbabwe');
